// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.17.3
// source: profession_service.proto

package position_service

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ProfessionServiseClient is the client API for ProfessionServise service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ProfessionServiseClient interface {
	Create(ctx context.Context, in *CreateProfession, opts ...grpc.CallOption) (*ProfessionId, error)
	GetAll(ctx context.Context, in *GetAllProfessionRequest, opts ...grpc.CallOption) (*GetAllProfessionResponse, error)
	GetById(ctx context.Context, in *ProfessionId, opts ...grpc.CallOption) (*Profession, error)
	Update(ctx context.Context, in *Profession, opts ...grpc.CallOption) (*Profession, error)
	Delete(ctx context.Context, in *ProfessionId, opts ...grpc.CallOption) (*AffectedRows, error)
}

type professionServiseClient struct {
	cc grpc.ClientConnInterface
}

func NewProfessionServiseClient(cc grpc.ClientConnInterface) ProfessionServiseClient {
	return &professionServiseClient{cc}
}

func (c *professionServiseClient) Create(ctx context.Context, in *CreateProfession, opts ...grpc.CallOption) (*ProfessionId, error) {
	out := new(ProfessionId)
	err := c.cc.Invoke(ctx, "/genproto.ProfessionServise/Create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *professionServiseClient) GetAll(ctx context.Context, in *GetAllProfessionRequest, opts ...grpc.CallOption) (*GetAllProfessionResponse, error) {
	out := new(GetAllProfessionResponse)
	err := c.cc.Invoke(ctx, "/genproto.ProfessionServise/GetAll", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *professionServiseClient) GetById(ctx context.Context, in *ProfessionId, opts ...grpc.CallOption) (*Profession, error) {
	out := new(Profession)
	err := c.cc.Invoke(ctx, "/genproto.ProfessionServise/GetById", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *professionServiseClient) Update(ctx context.Context, in *Profession, opts ...grpc.CallOption) (*Profession, error) {
	out := new(Profession)
	err := c.cc.Invoke(ctx, "/genproto.ProfessionServise/Update", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *professionServiseClient) Delete(ctx context.Context, in *ProfessionId, opts ...grpc.CallOption) (*AffectedRows, error) {
	out := new(AffectedRows)
	err := c.cc.Invoke(ctx, "/genproto.ProfessionServise/Delete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ProfessionServiseServer is the server API for ProfessionServise service.
// All implementations must embed UnimplementedProfessionServiseServer
// for forward compatibility
type ProfessionServiseServer interface {
	Create(context.Context, *CreateProfession) (*ProfessionId, error)
	GetAll(context.Context, *GetAllProfessionRequest) (*GetAllProfessionResponse, error)
	GetById(context.Context, *ProfessionId) (*Profession, error)
	Update(context.Context, *Profession) (*Profession, error)
	Delete(context.Context, *ProfessionId) (*AffectedRows, error)
	mustEmbedUnimplementedProfessionServiseServer()
}

// UnimplementedProfessionServiseServer must be embedded to have forward compatible implementations.
type UnimplementedProfessionServiseServer struct {
}

func (UnimplementedProfessionServiseServer) Create(context.Context, *CreateProfession) (*ProfessionId, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}
func (UnimplementedProfessionServiseServer) GetAll(context.Context, *GetAllProfessionRequest) (*GetAllProfessionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAll not implemented")
}
func (UnimplementedProfessionServiseServer) GetById(context.Context, *ProfessionId) (*Profession, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetById not implemented")
}
func (UnimplementedProfessionServiseServer) Update(context.Context, *Profession) (*Profession, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Update not implemented")
}
func (UnimplementedProfessionServiseServer) Delete(context.Context, *ProfessionId) (*AffectedRows, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Delete not implemented")
}
func (UnimplementedProfessionServiseServer) mustEmbedUnimplementedProfessionServiseServer() {}

// UnsafeProfessionServiseServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ProfessionServiseServer will
// result in compilation errors.
type UnsafeProfessionServiseServer interface {
	mustEmbedUnimplementedProfessionServiseServer()
}

func RegisterProfessionServiseServer(s grpc.ServiceRegistrar, srv ProfessionServiseServer) {
	s.RegisterService(&ProfessionServise_ServiceDesc, srv)
}

func _ProfessionServise_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateProfession)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProfessionServiseServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/genproto.ProfessionServise/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProfessionServiseServer).Create(ctx, req.(*CreateProfession))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProfessionServise_GetAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAllProfessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProfessionServiseServer).GetAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/genproto.ProfessionServise/GetAll",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProfessionServiseServer).GetAll(ctx, req.(*GetAllProfessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProfessionServise_GetById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProfessionId)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProfessionServiseServer).GetById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/genproto.ProfessionServise/GetById",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProfessionServiseServer).GetById(ctx, req.(*ProfessionId))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProfessionServise_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Profession)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProfessionServiseServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/genproto.ProfessionServise/Update",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProfessionServiseServer).Update(ctx, req.(*Profession))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProfessionServise_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProfessionId)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProfessionServiseServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/genproto.ProfessionServise/Delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProfessionServiseServer).Delete(ctx, req.(*ProfessionId))
	}
	return interceptor(ctx, in, info, handler)
}

// ProfessionServise_ServiceDesc is the grpc.ServiceDesc for ProfessionServise service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ProfessionServise_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "genproto.ProfessionServise",
	HandlerType: (*ProfessionServiseServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _ProfessionServise_Create_Handler,
		},
		{
			MethodName: "GetAll",
			Handler:    _ProfessionServise_GetAll_Handler,
		},
		{
			MethodName: "GetById",
			Handler:    _ProfessionServise_GetById_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _ProfessionServise_Update_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _ProfessionServise_Delete_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "profession_service.proto",
}
